server:
  port: 9000
spring:
  application:
    name: ribbon-consumer

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:1111/eureka,http://${eureka.instance.hostname}:1112/eureka
