server:
  port: 8082
spring:
  application:
    name: ribbon-consumer

eureka:
  instance:
    #ip-address: ${HOST_IP}
    #prefer-ip-address: true
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka
