server:
  port: 9001
spring:
  application:
    name: hello-server
eureka:
  instance:
    #ip-address: ${HOST_IP}
    #prefer-ip-address: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:1111/eureka
logging:
  level: info
